id BIVAR
solid BIVAR
visible BIVAR
persistent BIVAR
alarm BIVAR
x BIVAR
y BIVAR
xprevious BIVAR
yprevious BIVAR
xstart BIVAR
ystart BIVAR
sprite_index BIVAR
image_angle BIVAR
image_blend BIVAR
image_index BIVAR
image_alpha BIVAR
image_number BIVAR
image_speed BIVAR
image_xscale BIVAR
image_yscale BIVAR
mask_index BIVAR
friction BIVAR
gravity BIVAR
gravity_direction BIVAR
hspeed BIVAR
vspeed BIVAR
path_position BIVAR
path_positionprevious BIVAR
path_speed BIVAR
path_scale BIVAR
path_orientation BIVAR
path_endaction BIVAR
timeline_index BIVAR
timeline_running BIVAR
timeline_speed BIVAR
timeline_position BIVAR
timeline_loop BIVAR_END